
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#POSICIONTITCMT')) DROP TABLE #POSICIONTITCMT
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#INSTRUMENTOS')) DROP TABLE #INSTRUMENTOS
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#RPT_POSTIT_COMITENTES')) DROP TABLE #RPT_POSTIT_COMITENTES
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#RPT_POSTIT_COMITENTESND')) DROP TABLE #RPT_POSTIT_COMITENTESND
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#RPT_AGENTESDEPO')) DROP TABLE #RPT_AGENTESDEPO
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#POSTITMERCADOS')) DROP TABLE #POSTITMERCADOS

        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#POSICIONTITCMT')) DROP TABLE #POSICIONTITCMT
        CREATE TABLE #POSICIONTITCMT(CodComitente numeric(10,0) NOT NULL , NumComitente numeric(15,0) NOT NULL , Comitente varchar(80) COLLATE database_default  NOT NULL , TpComitente varchar(80) COLLATE database_default  NULL , CanalVta varchar(80) COLLATE database_default  NULL , EstaAnulado smallint NULL , CodEspecie numeric(10,0) NULL , CodInstrumento varchar(25) COLLATE database_default  NULL , CodTpInstrumento varchar(2) COLLATE database_default  NULL , TpInstrumento varchar(80) COLLATE database_default  NULL , CodigoInstrumento numeric(15,0) NULL , Instrumento varchar(150) COLLATE database_default  NULL , AbrevInstrumento varchar(30) COLLATE database_default  NULL , CodAgenteDepo numeric(3,0) NULL , Depositario varchar(80) COLLATE database_default  NULL , DepositarioCuenta varchar(30) COLLATE database_default  NULL , Cantidad numeric(22,10) NULL , CantidadNoDisponible numeric(22,10) NULL , CantidadTotal numeric(22,10) NULL , CodTpEspecie numeric(5,0) NULL , TpEspecie varchar(150) COLLATE database_default  NULL , AbrevEspIsin varchar(30) COLLATE database_default  NULL , CodMoneda numeric(5,0) NULL , Moneda varchar(80) COLLATE database_default  NULL , Importe numeric(19,2) NULL , ImporteMonPais numeric(19,2) NULL , ImporteMonPaisND numeric(19,2) NULL , ImporteMonPaisTotal numeric(19,2) NULL , Precio numeric(19,10) NULL , PrecioMonPais numeric(28,10) NULL , FechaUltCoti smalldatetime NULL , Teorica varchar(30) COLLATE database_default  NULL , CantAccionesLt numeric(22,10) NULL , CodOficial numeric(10,0) NULL , Oficial varchar(300) COLLATE database_default  NULL , Administrador varchar(300) COLLATE database_default  NULL , PorcValorResidual numeric(18,12) NULL , PrecioCieDol numeric(19,10) NULL , VMercadoDol numeric(19,2) NULL , FechaHasta smalldatetime NULL , PPP numeric(19,10) NULL , FechaPPP smalldatetime NULL , EMail varchar(255) COLLATE database_default  NULL , Telefono varchar(50) COLLATE database_default  NULL , PrecioMonDolar numeric(19,10) NULL , ImporteMonDolar numeric(19,2) NULL , FechaVencimiento smalldatetime NULL , InternalCode varchar(30) COLLATE database_default  NULL , DescCategoria varchar(80) COLLATE database_default  NULL , DescSectorInv varchar(80) COLLATE database_default  NULL , CmtBloqueado smallint NULL , CantidadVR numeric(22,10) NULL , Cusip varchar(30) COLLATE database_default  NULL , CodMercado numeric(5,0) NULL , Mercado varchar(80) COLLATE database_default  NULL , NumCmtMercado numeric(12,0) NULL , CUIT varchar(14) COLLATE database_default  NULL )
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#INSTRUMENTOS')) DROP TABLE #INSTRUMENTOS
        CREATE TABLE #INSTRUMENTOS(CodEspecie numeric(10,0) NOT NULL , CodSerie numeric(10,0) NULL , CodInstrumento varchar(25) COLLATE database_default  NULL , CodTpInstrumento varchar(2) COLLATE database_default  NULL , TpInstrumento varchar(80) COLLATE database_default  NULL , CodTpEspecie numeric(5,0) NULL , TpEspecie varchar(150) COLLATE database_default  NULL , Abreviatura varchar(30) COLLATE database_default  NULL , CodIndice numeric(10,0) NULL , Descripcion varchar(80) COLLATE database_default  NULL , CodigoEspecie numeric(15,0) NULL , AbrevEspIsin varchar(30) COLLATE database_default  NULL , CodMoneda numeric(5,0) NOT NULL , Moneda varchar(80) COLLATE database_default  NOT NULL , CodMonedaCot numeric(5,0) NULL , Precio numeric(19,10) NULL , PrecioMonPais numeric(28,10) NULL , FechaUltCoti smalldatetime NULL , Teorica varchar(30) COLLATE database_default  NULL , CodCotizacionEsp numeric(10,0) NULL , CodCotizacionSer numeric(10,0) NULL , CodCotizacionInd numeric(10,0) NULL , DescSectorInv varchar(80) COLLATE database_default  NULL , Cusip varchar(30) COLLATE database_default  NULL )
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#RPT_POSTIT_COMITENTES')) DROP TABLE #RPT_POSTIT_COMITENTES
        CREATE TABLE #RPT_POSTIT_COMITENTES(CodComitente numeric(10,0) NOT NULL , Descripcion varchar(80) COLLATE database_default  NULL , NumComitente numeric(15,0) NULL , EstaAnulado smallint NULL , CodOficial numeric(10,0) NULL , Oficial varchar(300) COLLATE database_default  NULL , Administrador varchar(300) COLLATE database_default  NULL , EMail varchar(255) COLLATE database_default  NULL , Telefono varchar(50) COLLATE database_default  NULL , TpComitente varchar(80) COLLATE database_default  NULL , CanalVta varchar(80) COLLATE database_default  NULL , DescCategoria varchar(80) COLLATE database_default  NULL , CmtBloqueado smallint NULL  PRIMARY KEY (CodComitente))
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#RPT_POSTIT_COMITENTESND')) DROP TABLE #RPT_POSTIT_COMITENTESND
        CREATE TABLE #RPT_POSTIT_COMITENTESND(CodInstrumento varchar(25) COLLATE database_default  NOT NULL , CodComitente numeric(10,0) NOT NULL , CantidadNoDisponible numeric(22,10) NOT NULL , CodAgenteDepo numeric(3,0) NULL )
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#RPT_AGENTESDEPO')) DROP TABLE #RPT_AGENTESDEPO
        CREATE TABLE #RPT_AGENTESDEPO(CodAgenteDepo numeric(3,0) NOT NULL , NumCuenta varchar(30) COLLATE database_default  NOT NULL , CodDepositario numeric(5,0) NOT NULL , Descripcion varchar(80) COLLATE database_default  NOT NULL )
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#POSTITMERCADOS')) DROP TABLE #POSTITMERCADOS
        CREATE TABLE #POSTITMERCADOS(CodMercado numeric(5,0) NULL , Descripcion varchar(80) COLLATE database_default  NULL )
        INSERT #INSTRUMENTOS (CodEspecie , CodTpEspecie ,Abreviatura, CodSerie , CodIndice , CodigoEspecie ,CodTpInstrumento, TpInstrumento , TpEspecie, CodInstrumento , CodMoneda , Moneda, AbrevEspIsin, DescSectorInv, Cusip)   select DISTINCT INSTRUMENTOS.CodEspecie, INSTRUMENTOS.CodTpEspecie, INSTRUMENTOS.Abreviatura, INSTRUMENTOS.CodSerie , INSTRUMENTOS.CodIndice, INSTRUMENTOS.Codigo , INSTRUMENTOS.CodTpInstrumento, TpInstrumento , TPESPECIE.Descripcion, COALESCE ('I' + CONVERT(Varchar(10),CodIndice), 'S' + CONVERT(Varchar(10),CodSerie) , 'E' + CONVERT(Varchar(10),INSTRUMENTOS.CodEspecie)) , ESPECIES.CodMoneda , MONEDAS.Descripcion, ABREVIATURASESP.Descripcion , SECTORESINV.Descripcion, ABREVCUSIP.Descripcion FROM dbo.vwInstrumentos INSTRUMENTOS INNER JOIN ESPECIES INNER JOIN MONEDAS ON MONEDAS.CodMoneda = ESPECIES.CodMoneda LEFT JOIN ABREVIATURASESP ON ABREVIATURASESP.CodEspecie = ESPECIES.CodEspecie AND CodTpAbreviatura = 'IS' ON ESPECIES.CodEspecie = INSTRUMENTOS.CodEspecie LEFT JOIN ABREVIATURASESP ABREVCUSIP ON ABREVCUSIP.CodEspecie = ESPECIES.CodEspecie AND ABREVCUSIP.CodTpAbreviatura = 'CS' LEFT JOIN TPESPECIE ON TPESPECIE.CodTpEspecie = INSTRUMENTOS.CodTpEspecie  LEFT JOIN SECTORESINV ON SECTORESINV.CodSectorInv = ESPECIES.CodSectorInv WHERE  ((DATEDIFF (day, '20200504', INSTRUMENTOS.FVencimiento) >= 0 OR INSTRUMENTOS.FVencimiento IS NULL)) AND ((UPPER(INSTRUMENTOS.Abreviatura) LIKE UPPER('tc20') ))
        INSERT #RPT_POSTIT_COMITENTES (CodComitente ,Descripcion, NumComitente ,CodOficial , Oficial, Administrador, EMail, Telefono, TpComitente, CanalVta, DescCategoria, CmtBloqueado )  select  COMITENTES.CodComitente , COMITENTES.Descripcion, COMITENTES.NumComitente ,OFICIAL.CodOperativo , OFICIAL.Apellido + ', ' + OFICIAL.Nombre, ADCARTERA.Apellido + ', ' + ADCARTERA.Nombre, LEFT(COMITENTES.EmailsInfo,255) , ISNULL(dbo.fnDomicilioEnt(0, COMITENTES.CodComitente, 'DO', 3), ISNULL(dbo.fnDomicilioEnt(0, COMITENTES.CodComitente, 'EC', 3), dbo.fnDomicilioEnt(0, COMITENTES.CodComitente, 'PA', 3))), TPCOMITENTE.Descripcion, CANALESVTA.Descripcion, CATEGORIAS.Descripcion,dbo.fnCmtBloqueado(COMITENTES.CodComitente) CmtBloqueado  FROM  COMITENTES  LEFT JOIN SUCURSALES ON COMITENTES.CodSucursal = SUCURSALES.CodSucursal LEFT JOIN OPERATIVOSROLCMT OFICIALROL INNER JOIN OPERATIVOS OFICIAL ON OFICIAL.CodOperativo = OFICIALROL.CodOperativo AND OFICIALROL.CodRol = 'OC'  ON OFICIALROL.CodComitente = COMITENTES.CodComitente  LEFT JOIN OPERATIVOSROLCMT ADCARTERAROL INNER JOIN OPERATIVOS ADCARTERA ON ADCARTERA.CodOperativo = ADCARTERAROL.CodOperativo AND ADCARTERAROL.CodRol = 'AC'  ON ADCARTERAROL.CodComitente = COMITENTES.CodComitente  LEFT JOIN TPCOMITENTE ON COMITENTES.CodTpComitente = TPCOMITENTE.CodTpComitente  LEFT JOIN CANALESVTA ON COMITENTES.CodCanalVta = CANALESVTA.CodCanalVta  LEFT JOIN CARTERASADMINCMTHIST     INNER JOIN CARTERASADMIN ON CARTERASADMIN.CodCarteraAdmin = CARTERASADMINCMTHIST.CodCarteraAdmin ON CARTERASADMINCMTHIST.CodComitente = COMITENTES.CodComitente AND (('20200504' >= CARTERASADMINCMTHIST.FechaIngreso AND FechaEgreso IS NULL ) OR '20200504' BETWEEN CARTERASADMINCMTHIST.FechaIngreso AND DATEADD(day,-1, CARTERASADMINCMTHIST.FechaEgreso)) LEFT JOIN CATEGORIAS ON CATEGORIAS.CodCategoria = COMITENTES.CodCategoria  WHERE ((COMITENTES.NumComitente = ))
        INSERT #RPT_AGENTESDEPO (CodAgenteDepo, NumCuenta, CodDepositario, Descripcion)  select AGENTESDEPO.CodAgenteDepo, AGENTESDEPO.NumCuenta, AGENTESDEPO.CodDepositario, DEPOSITARIOS.Descripcion FROM DEPOSITARIOS INNER JOIN AGENTESDEPO ON AGENTESDEPO.CodDepositario = DEPOSITARIOS.CodDepositario WHERE ((UPPER(DEPOSITARIOS.Descripcion) LIKE UPPER('CAJA DE VALORES') ))
        INSERT #POSTITMERCADOS (CodMercado, Descripcion)  select CodMercado, Descripcion FROM MERCADOS
        exec spINFO_PosicionTitCmt_Precios @FechaHasta='20200505'
        exec spINFO_PosicionTitCmt_Insert @EsPorConcertacion=0,@FechaHasta='20200505',@EsPorMercado=0,@EsConDepositario=-1
        exec sp_appCENTCONFIGURACIONUSER @CodAccion='ENTCONFIGUSERd',@CodUsuario=35,@CodEntidad=161
        select ConLineasH, ConLineasV, NumeraHojas FROM appENTCONFIGURACIONUSER WHERE CodEntidad = 161 AND CodUsuario = 35 AND CodEntConfiguracionUser = 'PRUEBA ROFEX OLI'
        select COALESCE(EsImpresionHoriz,-1) EsImpresionHoriz  FROM appENTIDADES WHERE CodEntidad = 161
        select SentenciaSQL, COALESCE(PermiteModificarCol,-1) PermiteModificarCol, COALESCE(PermiteModificarOrd,-1) PermiteModificarOrd, COALESCE(PermiteModificarFn,-1) PermiteModificarFn, COALESCE(PermiteModificarCrt,-1) PermiteModificarCrt, COALESCE(FntColSize,8) FntColSize, COALESCE(FntColName,'Arial') FntColName, COALESCE(FntEncName,'Arial') FntEncName, COALESCE(FntEncSize,8) FntEncSize , COALESCE(FntEncBold,-1) FntEncBold, EsMultiLenguaje FROM appENTIDADES WHERE CodEntidad = 161
        exec sp_appCENTCOLUMNASUSER @CodEntConfiguracionUser='PRUEBA ROFEX OLI',@CodUsuario=35,@CodEntidad=161
        exec sp_appCENTCORTESUSER @CodEntConfiguracionUser='PRUEBA ROFEX OLI',@CodUsuario=35,@CodEntidad=161
        exec sp_appCENTFUNCIONESUSER @CodEntConfiguracionUser='PRUEBA ROFEX OLI',@CodUsuario=35,@CodEntidad=161

        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#GRILLA_44681')) DROP TABLE #GRILLA_44681
        CREATE TABLE #GRILLA_44681(FMT_GRILLA varchar(80) COLLATE database_default  NULL , DepositarioCuenta varchar(30) COLLATE database_default  NULL , Depositario varchar(80) COLLATE database_default  NULL , NumComitente numeric(15,0) NULL , Comitente varchar(80) COLLATE database_default  NULL , Oficial varchar(300) COLLATE database_default  NULL , CodigoInstrumento numeric(15,0) NULL , AbrevInstrumento varchar(30) COLLATE database_default  NULL , Cantidad numeric(22,10) NULL , ImporteMonPais numeric(19,2) NULL , PorcVResidual numeric(18,12) NULL , Administrador varchar(300) COLLATE database_default  NULL , CantidadNoDisponible numeric(22,10) NULL , CantidadTotal numeric(22,10) NULL , CantidadVDolar numeric(19,2) NULL , ImporteMonPaisND numeric(19,2) NULL , ImporteMonPaisTotal numeric(19,2) NULL , CantidadVR numeric(22,10) NULL , CodComitente numeric(10,0) NULL , CanalVta varchar(80) COLLATE database_default  NULL , DescCategoria varchar(80) COLLATE database_default  NULL , Contacto numeric(10,0) NULL , CUIT varchar(14) COLLATE database_default  NULL , CmtEMail varchar(4000) COLLATE database_default  NULL , CmtBloqueado smallint NULL , Estado varchar(30) COLLATE database_default  NULL , CmtTelefono varchar(50) COLLATE database_default  NULL , TpComitente varchar(80) COLLATE database_default  NULL , Precio numeric(19,10) NULL , CotizaDolar numeric(19,10) NULL , PrecioMonPais numeric(19,10) NULL , CodAgenteDepo numeric(3,0) NULL , FechaPPP smalldatetime NULL , FechaHasta smalldatetime NULL , FechaUltCoti smalldatetime NULL , FXRate numeric(19,10) NULL , Importe numeric(19,2) NULL , CodInstrumento varchar(25) COLLATE database_default  NULL , Cusip varchar(30) COLLATE database_default  NULL , Instrumento varchar(150) COLLATE database_default  NULL , FechaVencimiento smalldatetime NULL , InternalCode varchar(30) COLLATE database_default  NULL , AbrevEspIsin varchar(30) COLLATE database_default  NULL , CodMercado numeric(5,0) NULL , DescMercado varchar(80) COLLATE database_default  NULL , NumCmtMercado numeric(12,0) NULL , Moneda varchar(80) COLLATE database_default  NULL , CodMoneda numeric(5,0) NULL , CodOficial numeric(10,0) NULL , PPP numeric(19,10) NULL , DescSectorInv varchar(80) COLLATE database_default  NULL , TpEspecie varchar(150) COLLATE database_default  NULL , CodTpEspecie numeric(5,0) NULL , TpInstrumento varchar(80) COLLATE database_default  NULL , CodTpInstrumento varchar(2) COLLATE database_default  NULL , PrecioCieDol numeric(19,10) NULL , VMercadoDol numeric(19,2) NULL , Teorica varchar(30) COLLATE database_default  NULL , IDPosicion numeric(10,0) IDENTITY(1, 1) NOT NULL , DFPaginacion numeric(10,0) NULL  PRIMARY KEY (IDPosicion))
        INSERT #GRILLA_44681  select 'Posición de Títulos de Comitentes', #POSICIONTITCMT.DepositarioCuenta, #POSICIONTITCMT.Depositario, #POSICIONTITCMT.NumComitente, #POSICIONTITCMT.Comitente, #POSICIONTITCMT.Oficial, #POSICIONTITCMT.CodigoInstrumento, #POSICIONTITCMT.AbrevInstrumento, #POSICIONTITCMT.Cantidad, #POSICIONTITCMT.ImporteMonPais, #POSICIONTITCMT.PorcValorResidual, #POSICIONTITCMT.Administrador, #POSICIONTITCMT.CantidadNoDisponible, #POSICIONTITCMT.CantidadTotal, #POSICIONTITCMT.ImporteMonDolar, #POSICIONTITCMT.ImporteMonPaisND, #POSICIONTITCMT.ImporteMonPaisTotal, #POSICIONTITCMT.CantidadVR, #POSICIONTITCMT.CodComitente, #POSICIONTITCMT.CanalVta, #POSICIONTITCMT.DescCategoria, #POSICIONTITCMT.CodComitente, #POSICIONTITCMT.CUIT, REPLACE(EMail, CHAR(13) + CHAR(10),' '), #POSICIONTITCMT.CmtBloqueado, CASE WHEN EstaAnulado = -1 THEN 'Anulado' ELSE 'Activo' END, #POSICIONTITCMT.Telefono, #POSICIONTITCMT.TpComitente, #POSICIONTITCMT.Precio, #POSICIONTITCMT.PrecioMonDolar, #POSICIONTITCMT.PrecioMonPais, #POSICIONTITCMT.CodAgenteDepo, #POSICIONTITCMT.FechaPPP, #POSICIONTITCMT.FechaHasta, #POSICIONTITCMT.FechaUltCoti, (select dbo.fnCotizacionMon(FechaHasta, CodMoneda, dbo.fnTraerMonedaPaisApl()) Cotizacion from MONEDAS Where CodIDMoneda = 'DO'), #POSICIONTITCMT.Importe, #POSICIONTITCMT.CodInstrumento, #POSICIONTITCMT.Cusip, #POSICIONTITCMT.Instrumento, #POSICIONTITCMT.FechaVencimiento, #POSICIONTITCMT.InternalCode, #POSICIONTITCMT.AbrevEspIsin, #POSICIONTITCMT.CodMercado, #POSICIONTITCMT.Mercado, #POSICIONTITCMT.NumCmtMercado, #POSICIONTITCMT.Moneda, #POSICIONTITCMT.CodMoneda, #POSICIONTITCMT.CodOficial, #POSICIONTITCMT.PPP, #POSICIONTITCMT.DescSectorInv, #POSICIONTITCMT.TpEspecie, #POSICIONTITCMT.CodTpEspecie, #POSICIONTITCMT.TpInstrumento, #POSICIONTITCMT.CodTpInstrumento, #POSICIONTITCMT.PrecioCieDol, #POSICIONTITCMT.VMercadoDol, #POSICIONTITCMT.Teorica,  0 FROM #POSICIONTITCMT LEFT JOIN CMTJURIDICOS ON #POSICIONTITCMT.CodComitente = CMTJURIDICOS.CodComitente
        select Count(*) as Cantidad FROM #GRILLA_44681
        UPDATE #GRILLA_44681 SET DFPaginacion = 0
        SELECT TOP 1 COUNT(IDPosicion) CantidadReg FROM #GRILLA_44681 GROUP BY #GRILLA_44681.FMT_GRILLA,#GRILLA_44681.CodAgenteDepo,#GRILLA_44681.DepositarioCuenta,#GRILLA_44681.Depositario
        select DISTINCT #GRILLA_44681.FMT_GRILLA,#GRILLA_44681.CodAgenteDepo,#GRILLA_44681.DepositarioCuenta,#GRILLA_44681.Depositario FROM #GRILLA_44681 ORDER BY  #GRILLA_44681.FMT_GRILLA ASC, #GRILLA_44681.CodAgenteDepo ASC
        select MONEDAS.CodMoneda FROM MONEDAS INNER JOIN PAISES     INNER JOIN AGENTES        INNER JOIN  PARAMETROSREL ON AGENTES.CodAgente = PARAMETROSREL.CodAgente     ON AGENTES.CodPais = PAISES.CodPais  ON PAISES.CodMoneda = MONEDAS.CodMoneda 
        select SUM(Cantidad) as K_1 ,SUM(CantidadNoDisponible) as K_2 ,COUNT(NumComitente) as K_3  FROM #GRILLA_44681 WHERE FMT_GRILLA = 'Posición de Títulos de Comitentes' AND CodAgenteDepo = 2
        select NumComitente,Comitente,Oficial,CodigoInstrumento,AbrevInstrumento,Cantidad,ImporteMonPais,IDPosicion FROM #GRILLA_44681 WHERE FMT_GRILLA = 'Posición de Títulos de Comitentes' AND CodAgenteDepo = 2 ORDER BY NumComitente ASC,ImporteMonPais DESC

            