<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('max_execution_time', 300);

$dbh = $dbh = new PDO ("sqlsrv:server=srv-vbolsa0;database=test","sa","25DeMayo");
/*
$sql = "set nocount on \n
        declare @pFecha Char(8) \n
        select @pFecha = CONVERT(VARCHAR(8),GETDATE(),112) \n
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#RPT_POSMONCMT_CMT')) DROP TABLE #RPT_POSMONCMT_CMT \n
        CREATE TABLE #RPT_POSMONCMT_CMT(CodComitente numeric(10,0) NULL , Descripcion varchar(80) COLLATE database_default  NULL , TpComitente varchar(80) COLLATE database_default  NULL , Contacto varchar(80) COLLATE database_default  NULL , NumComitente numeric(15,0) NULL , EstaAnulado smallint NULL , EmailsInfo varchar(4000) COLLATE database_default  NULL , CodOficial numeric(10,0) NULL , CodReferente numeric(10,0) NULL , CodAdministrador numeric(10,0) NULL , Oficial varchar(80) COLLATE database_default  NULL , Referente varchar(80) COLLATE database_default  NULL , Administrador varchar(80) COLLATE database_default  NULL , CanalVenta varchar(80) COLLATE database_default  NULL , Categoria varchar(80) COLLATE database_default  NULL ) \n
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#RPT_POSMONCMT_MON')) DROP TABLE #RPT_POSMONCMT_MON \n
        CREATE TABLE #RPT_POSMONCMT_MON(CodMoneda numeric(5,0) NULL , Descripcion varchar(80) COLLATE database_default  NULL , Simbolo varchar(10) COLLATE database_default  NULL ) \n
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#RPT_POSMONCMT_FINAL')) DROP TABLE #RPT_POSMONCMT_FINAL \n
        CREATE TABLE #RPT_POSMONCMT_FINAL(CodComitente numeric(10,0) NULL , Descripcion varchar(80) COLLATE database_default  NULL , TpComitente varchar(80) COLLATE database_default  NULL , Contacto varchar(80) COLLATE database_default  NULL , NumComitente numeric(15,0) NULL , EstaAnulado smallint NULL , EmailsInfo varchar(4000) COLLATE database_default  NULL , CodOficial numeric(10,0) NULL , CodReferente numeric(10,0) NULL , CodAdministrador numeric(10,0) NULL , Oficial varchar(80) COLLATE database_default  NULL , Referente varchar(80) COLLATE database_default  NULL , Administrador varchar(80) COLLATE database_default  NULL , SaldoDisponible numeric(19,2) NULL , CodMoneda numeric(5,0) NULL , DescMoneda varchar(80) COLLATE database_default  NULL , Simbolo varchar(10) COLLATE database_default  NULL , TieneInstruccion varchar(4000) COLLATE database_default  NULL , SaldoNoDisponible numeric(19,2) NULL , SaldoTotal numeric(19,2) NULL , CanalVenta varchar(80) COLLATE database_default  NULL , Categoria varchar(80) COLLATE database_default  NULL , TieneSaldoCeroDisponible smallint NULL ) \n
        INSERT  #RPT_POSMONCMT_CMT (CodComitente, Descripcion, NumComitente, Contacto, EmailsInfo, EstaAnulado, CodOficial, CodReferente, CodAdministrador, Oficial, Referente, Administrador, TpComitente, CanalVenta,Categoria)  select  COMITENTES.CodComitente, COMITENTES.Descripcion, COMITENTES.NumComitente, COMITENTES.Contacto, COMITENTES.EmailsInfo,  COMITENTES.EstaAnulado, OFICIAL.CodOperativo, REFERENTE.CodOperativo, ADCARTERA.CodOperativo, OFICIAL.Apellido + ', ' + OFICIAL.Nombre,  REFERENTE.Apellido + ', ' + REFERENTE.Nombre, ADCARTERA.Apellido + ', ' + ADCARTERA.Nombre , TPCOMITENTE.Descripcion, CANALESVTA.Descripcion,CATEGORIAS.Descripcion FROM  COMITENTES    LEFT JOIN CATEGORIAS ON COMITENTES.CodCategoria = CATEGORIAS.CodCategoria   LEFT JOIN CANALESVTA ON COMITENTES.CodCanalVta = CANALESVTA.CodCanalVta   LEFT JOIN TPCOMITENTE ON COMITENTES.CodTpComitente = TPCOMITENTE.CodTpComitente   LEFT JOIN OPERATIVOSROLCMT OPERROLREF  INNER JOIN OPERATIVOS REFERENTE ON REFERENTE.CodOperativo = OPERROLREF.CodOperativo   ON COMITENTES.CodComitente = OPERROLREF.CodComitente    AND OPERROLREF.CodRol = 'RE'  LEFT JOIN OPERATIVOSROLCMT  INNER JOIN OPERATIVOS OFICIAL ON OFICIAL.CodOperativo = OPERATIVOSROLCMT.CodOperativo  ON COMITENTES.CodComitente = OPERATIVOSROLCMT.CodComitente  AND OPERATIVOSROLCMT.CodRol = 'OC'  LEFT JOIN OPERATIVOSROLCMT ADCARTERAROL  INNER JOIN OPERATIVOS ADCARTERA ON ADCARTERA.CodOperativo = ADCARTERAROL.CodOperativo  ON COMITENTES.CodComitente = ADCARTERAROL.CodComitente  AND ADCARTERAROL.CodRol = 'AC'  LEFT JOIN CARTERASADMINCMTHIST INNER JOIN CARTERASADMIN ON CARTERASADMIN.CodCarteraAdmin = CARTERASADMINCMTHIST.CodCarteraAdmin ON CARTERASADMINCMTHIST.CodComitente = COMITENTES.CodComitente AND ((GETDATE() >= CARTERASADMINCMTHIST.FechaIngreso AND FechaEgreso IS NULL ) OR GETDATE() BETWEEN CARTERASADMINCMTHIST.FechaIngreso AND DATEADD(day,-1, CARTERASADMINCMTHIST.FechaEgreso)) \n
        INSERT #RPT_POSMONCMT_MON (CodMoneda, Descripcion, Simbolo)  select  CodMoneda, Descripcion, Simbolo  FROM  MONEDAS  \n
        exec spINFO_PosicionMonCmt @PorConcertacion=0,@Fecha=@pFecha \n
        IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#GRILLA_70554751')) DROP TABLE #GRILLA_70554751 \n
        CREATE TABLE #GRILLA_70554751(FMT_GRILLA varchar(80) COLLATE database_default  NULL , Oficial varchar(150) COLLATE database_default  NULL , Moneda varchar(80) COLLATE database_default  NULL , SimbMoneda varchar(10) COLLATE database_default  NULL , NumComitente numeric(15,0) NULL , DescComitente varchar(80) COLLATE database_default  NULL , SaldoDisponible numeric(19,2) NULL , CodAdministrador numeric(10,0) NULL , Administrador varchar(150) COLLATE database_default  NULL , CanalVenta varchar(80) COLLATE database_default  NULL , CodComitente numeric(10,0) NULL , Categoría varchar(80) COLLATE database_default  NULL , CmtContacto varchar(80) COLLATE database_default  NULL , Contacto numeric(10,0) NULL , CmtEMail varchar(4000) COLLATE database_default  NULL , CmtTelefono varchar(50) COLLATE database_default  NULL , TpComitente varchar(80) COLLATE database_default  NULL , EstaAnulado smallint NULL , CodMoneda numeric(10,0) NULL , CodOficial numeric(10,0) NULL , Referente varchar(150) COLLATE database_default  NULL , CodReferente numeric(10,0) NULL , SaldoNoDisponible numeric(19,2) NULL , SaldoTotal numeric(19,2) NULL , TieneInstruccion varchar(4000) COLLATE database_default  NULL , IDPosicion numeric(10,0) IDENTITY(1, 1) NOT NULL , DFPaginacion numeric(10,0) NULL  PRIMARY KEY (IDPosicion)) \n
        INSERT #GRILLA_70554751  select 'Posición Monetaria de Comitentes', #RPT_POSMONCMT_FINAL.Oficial, #RPT_POSMONCMT_FINAL.DescMoneda, #RPT_POSMONCMT_FINAL.Simbolo, #RPT_POSMONCMT_FINAL.NumComitente, #RPT_POSMONCMT_FINAL.Descripcion, #RPT_POSMONCMT_FINAL.SaldoDisponible, #RPT_POSMONCMT_FINAL.CodAdministrador, #RPT_POSMONCMT_FINAL.Administrador, #RPT_POSMONCMT_FINAL.CanalVenta, #RPT_POSMONCMT_FINAL.CodComitente, #RPT_POSMONCMT_FINAL.Categoria, #RPT_POSMONCMT_FINAL.Contacto, #RPT_POSMONCMT_FINAL.CodComitente, REPLACE(#RPT_POSMONCMT_FINAL.EmailsInfo, CHAR(13) + CHAR(10),' '), ISNULL(dbo.fnDomicilioEnt(0, #RPT_POSMONCMT_FINAL.CodComitente, 'DO', 3), ISNULL(dbo.fnDomicilioEnt(0, #RPT_POSMONCMT_FINAL.CodComitente, 'EC', 3), dbo.fnDomicilioEnt(0, #RPT_POSMONCMT_FINAL.CodComitente, 'PA', 3))), #RPT_POSMONCMT_FINAL.TpComitente, #RPT_POSMONCMT_FINAL.EstaAnulado, #RPT_POSMONCMT_FINAL.CodMoneda, #RPT_POSMONCMT_FINAL.CodOficial, #RPT_POSMONCMT_FINAL.Referente, #RPT_POSMONCMT_FINAL.CodReferente, #RPT_POSMONCMT_FINAL.SaldoNoDisponible, #RPT_POSMONCMT_FINAL.SaldoTotal, #RPT_POSMONCMT_FINAL.TieneInstruccion,  0 FROM  #RPT_POSMONCMT_FINAL  \n
        select NumComitente, SimbMoneda, DescComitente, SaldoDisponible from #GRILLA_70554751 
        where SimbMoneda in ('$') and SaldoDisponible > 0 \n
        set nocount off \n";
*/

$sql = "exec sp_disponible";
$stmt = $dbh->prepare($sql);
$stmt->execute();
$results=$stmt->fetch(PDO::FETCH_ASSOC);        
unset($stmt);
$sql = "select NumComitente, SimbMoneda, DescComitente, SaldoDisponible from GRILLA_70554751 where SimbMoneda in ('$') and SaldoDisponible > 0";
$stmt = $dbh->prepare($sql);
$stmt->execute();
$results=$stmt->fetchAll(PDO::FETCH_ASSOC);        
unset($stmt);

print_r($results);
